### ISSUE TITLE
Lists can't be passed to List.foldLeft?

### ISSUE THREAD

**Issue by mlms13** [reazen/relude#126]
The following very reasonable code fails to compile:

```reason
let doInOrder = (go: 'a => Js.Promise.t('b), data: list('a)) =>
  Relude.List.foldLeft(
    (acc, curr) =>
      flatMap(promises => map(v => [v, ...promises], go(curr)), acc),
    pure([]),
    data,
  );
```

The compiler says:

```
  This has type:
    list('a)
  But somewhere wanted:
    BsAbstract.List.Foldable.t('a)
```

Leaving off the type annotation on `data` in the function signature allows the compiler to infer the right type, but it seems like we're getting bad type hints from the rei files?

**Comment by andywhite37** [comment]
I get the example, but where are `flatMap`, `map`, and `pure` coming from for Js.Promise?

**Comment by mlms13** [comment]
Oh, that was in `Elude`... I was replacing lots of functions with their Relude equivalents before archiving it.

**Comment by andywhite37** [comment]
Ah ok, got it

**Comment by andywhite37** [comment]
I was curious if the problem had something to do with how the type params line up with the `BsAbstract.Interface.FOLDABLE with type t('a) = list('a)`.  That code is a little squirrley.

I'm also now thinking that it might be interesting to write the FUNCTOR/APPLY/etc. typeclasses for Js.Promise.t.  There's a function `foldWithMonad` in FoldableExtensions, (which is the same as foldM` in haskell/purescript), which is similar to what you're doing.  If we had `MONAD` for `Promise`, this function might just come for free.

**Comment by mlms13** [comment]
It looks like the rei files were freshly generated, and I've never had luck getting the generated interfaces to work will with module functors, but if you can find anything useful in the `with type ,,,` part, that would be amazing.

I considered adding more functions/typleclass implementation to Promise, but honestly I'm not convinced promises are worth it. I think it's fine to make it as easy as possible to get out of Promises, and leave it at that. I was mostly updating Elude for the sake of giving it a dignified death, but the only thing it's still being used for is its Ordering definition and I'd like to get away from that as well.

**Comment by andywhite37** [comment]
Yeah, I regenerated the .rei files when all the extension stuff changed, because I wanted to see what the changes to the interface would be, and to allow ourselves an opportunity to re-generate the diff the .rei files if things change under the hood.  I know we lost the docs and any hand-edits by doing that, and someday I plan to restore the docs if we can find a sane way to manage it.

I was curious if we annotated the types in List_Instances if they would come through in the .rei files, but I know that's kind of backwards.  I'm sort of questioning the value of having the .rei files at this point, mostly because there's not a sane way to manage them with documentation and with the extensive use of all the extensions/includes.  However, I'm also not in love with having the huge doc blocks in the .re files, but I'm not sure how best to manage all these things.

**Comment by mlms13** [comment]
Yeah, if we have to have full type annotations for every function in the `re` files just to get the `rei` files to generate correctly, and we lose docs every time we regen the `rei`s, it's a little hard to justify having them at all. Unless we're willing to generate them once up front, then write them by hand for all of eternity, without any idea whether we've forgotten to include "for free" functions.

**Comment by mlms13** [comment]
Just an update, in case anyone else is following along...

We figured out that the generated `rei` files include references to e.g. `BsAbstract.List.Foldable.t('a)`, which is actually a `list('a)`, but the compiler doesn't seem to reconcile those two types unless the project includes `bs-abstract` in its `bsconfig.json`, so for now we have `bs-abstract` as a `peerDependency`, and we've updated the docs with better installation instructions to address this.

Longer term, we still don't have a great solution for this. (Re-) generating `rei` files is the only sane path forward, since adding a function to `Foldables` shouldn't require manually changing `List`, `Array`, `Option`, etc, but the generated interfaces blow out documentation comments and produce some fairly incomprehensible type signatures.

**Comment by andywhite37** [comment]
We might be able to insulate ourselves from exposing bs-abstract things publicly by aliasing things in the right places.  That might be the easiest way to avoid the bs-abstract issues.  I also don't think it's that big of a deal to tell people to put `bs-abstract` in their bsconfig.json.

**Comment by mlms13** [comment]
I'm not too concerned about expecting downstream projects to list `bs-abstract` either, but it's kind of a pain that the type hints look like `BsAbstract.Foldable.List.t(BsAbstract.Monoid.String.t) => ...`. You can figure out what it does, but it's a lot more mental overhead than `list(string)`. Hopefully adding more annotations will help us work around this.

**Comment by andywhite37** [comment]
Oh yeah, I forgot that getting the more specific type signatures in there was part of the problem.  I suspect it will be difficult to get that to work with the extensions/include stuff, since the types don't seem to pickup on the `with type t('a) = list('a)` annotations at the module level.  I now remember we were talking about asking if there was anything that could be done there in bucklescript, but that kind of fizzled out.

**Comment by andywhite37** [comment]
@mlms13 - what do we want to do with this ticket at this point?  I think the core issue is the .rei generation problem - is that right?

**Comment by andywhite37** [comment]
Here is the repo I made to demonstrate how the types come out in the .rei files, for modules that have the `with type t('a) = option('a)` style annotations:

https://github.com/andywhite37/bs-rei-gen-example/blob/master/src/Instances.rei#L4

**Comment by mlms13** [comment]
I'm happy to close this. I don't think there's any immediate next steps... we know at some point we want better tooling to help with interface files, but until then, hand-editing the interfaces isn't a great option, so there isn't much we can do about this issue.
