### ISSUE TITLE
Strange type incompatibility between array and BsAbstract.Array.Foldable.t

### ISSUE THREAD

**Issue by scull7** [reazen/relude#162]
I haven't been able to distill this case, but I'm getting a weird type error where `array(string)` is incompatible with `BsAbstract.Array.Foldable.t(string). Not sure what's going on

relude:  0.26.0
bs-abstract: 0.17.0

Error: 
![Screenshot 2019-08-24 23 11 11](https://user-images.githubusercontent.com/234352/63646297-3d406c80-c6c5-11e9-82ff-127b21c0e28a.png)

```reason
open relude.globals;

exception BasePathNotAbsolute(string);

module BasePath = {
  let resolve = (baseDir, filename) =>
    Node.Path.isAbsolute(baseDir)
      ? Node.Path.resolve(baseDir, filename)
      : raise(BasePathNotAbsolute(baseDir));
};

module Nconf = {
  type t;

  [@bs.module] external nconf: t = "nconf";

  module Format = {
    type t;

    [@bs.module] external toml: t = "nconf-toml";
  };

  [@bs.module "nconf"] external formats: Js.Dict.t(Format.t) = "format";

  // Initialize the TOML format.
  Js.Dict.set(formats, "toml", Format.toml);

  [@bs.send] external argv: t => t = "argv";

  [@bs.send] external env: (t, string) => t = "env";

  module FileOptions = {
    [@bs.deriving abstract]
    type t = {
      file: string,
      format: Format.t,
    };
  };

  [@bs.send] external file: (t, string, FileOptions.t) => unit = "file";

  let file = (~format=Format.toml, ~path, ~name, t) => {
    let _ = FileOptions.t(~file=path, ~format) |> file(t, name);
    t;
  };

  let addFiles = (baseDir, fileNames: array(string), t) => {
    let reducer = (filename, t) => {
      let name = Node.Path.basename(filename);
      let path = BasePath.resolve(baseDir, filename);

      file(~path, ~name, t);
    };

    Array.foldRight(reducer, t, fileNames);
  };
};

module SelectN = {
  [@bs.module]
  external get: (string, Js.Json.t) => Js.Null_undefined.t(Js.Json.t) =
    "selectn";
};

let make = (~files=[|"environment.toml", "defaults.toml"|], configPath) => {
  Nconf.nconf
  |> Nconf.argv
  |> (t => Nconf.env(t, "__"))
  |> Nconf.addFiles(configPath, files);
};

```

**Comment by mlms13** [comment]
Do you have `bs-abstract` included as a dependency in your `bsconfig.json`? Unfortunately, the inferred types get really messy with all of the first-class module stuff, and they often resolve to typeclass instances (e.g. `BsAbstract.List.Foldable` or `BsAbstract.String.Monoid`) instead of simple types. The compiler seems to only understand the compatibility if `bs-abstract` is explicitly listed as a dependency,

We've considered working around this by maintaining interface files (#109, #126), but with all of the `include`'d modules, the tooling seems not great for determining when the interface files should be updated (e.g., if a function is added to `ApplyExtras`, that affects list, array, option, and many more, and those have to be manually tracked down).

**Comment by scull7** [comment]
Thank you for the detailed and thoughtful to response to my not so smart in the moment question. 😄 I had included bs-abstract in my `package.json` file but had forgotten to add it to the `bsconfig.json` file.

**Comment by mlms13** [comment]
No worries! I ran into the exact same thing with a new project, and it took me a surprisingly long time to figure it out. :) It would be nice if bsconfig would have the concept of `peerDependencies` to add some hints when this kind of error comes up. Hopefully someday we'll come up with a good strategy for `rei` files, which will clean this up.

**Comment by scull7** [comment]
Yes, a warning of some sort would be nice.  Hopefully, this will be in my mind for the next time.
