### ISSUE TITLE
Bundle size as it relates to module functor use, and its js/runtime representation

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#169]
I'm opening this ticket as a bit of a placeholder for some things @mlms13 has been investigating about functors, and the generated .js code.

In many cases the use of module functors results in actual runtime javascript function calls to spit out "modules."  Example:  https://github.com/mlms13/bsb-520-include/blob/master/src/SemiringExtras.bs.js#L6-L11

This doesn't work well with tree shaking/dead code elimination, because the result is a runtime JS object, as opposed to statically-analyzable code.

@mlms13 made a hypothesis that the compiler did a better job at optimizing and inlining things within the same file, and tried an experiment where he put all the code for his `bsb-520-include` example in a single "file" and it turns out the compiler seems to be optimizing away a module functor application, and therefore seems to make the module pure, whereas it's impure when the code is in separate files.  This strikes me a little odd in general, but I don't know what's expected in ocaml, and how this relates to incremental compilation challenges.  The impurity issue is #168 - this issue is more about functors being represented as JS functions or inlined.

https://reasonml.github.io/en/try.html?rrjsx=true&reason=LYewJgrgNgpgBASQHYBcYCcBmBDAxvAXjgG8AoOOUSWOFATwAd4BlGYAS3XaQHM4iyFCvSa0A3OSGwUcbGDAAuOAAoUAGloBKfgD5xkitMrQlqjSm0E9KCULhGAXhhBKbB+zBkgkMV7bgAvhJBpKRU0CxsnNw8AKIAHijo2ADO-CSS4TQAstgA1oQqzErIaFh4MAB0rBxcvJZ6glKecNy46GwwqOnMlXJgyr3eMJr+ISFh4BFwACJsIOlNWfClNdG8JagYOPjVUXV8AO7sKAAWtIzwMkTc1xl2Ilfpt-6GLf3pygDUo+5GwNBPnAAFRwX52RzOdIABleHi8PnSAEYxhJJG0oBAwJFajEEklUpVcgVlKt9jFfpIjAA3Z5IdqdVDKADMvxCQA

One thing thing we were curious to try would be to essentially concatenate all the modules in Relude into a single .re file (likely wrapping each file in it's own module), and then just compile that single .re file.  In theory, if module functors are inlined throughout, there'd be more opportunity for dead code elimination.  We're not saying this is the right way to distribute the lib - it's more of an experiment.

**Comment by mlms13** [comment]
Thanks for opening this! I think it's important that we tease apart the two separate issues:

- Module functors are deemed impure, leading to unused imports (#168). This ultimately only adds 10% or so to the bundle size, and can be worked around with Rollup flags.
- Module functors produce JS objects, loaded with functions that may or may not be used, and JS-based tree-shaking utilities are unable to remove dead code.

I think solving the second issue will have a _much_ bigger impact on the bundled size of Relude. As @andywhite37 said, the current working theory is that putting everything into one file would all the code to compile in a way where module-application is solved at compile-time instead of runtime, and it should produce code that tree-shakes beautifully.

Dumping everything into a single file would obviously create a miserable dev experience while working on Relude itself, but if we could find a way to script this out before publishing to npm, that _might_ solve the issue for downstream projects that depend on Relude.

**Comment by mlms13** [comment]
CC @arecvlohe, in case you want to follow along, because I think this is probably closer to what you were getting at in the issue you opened.

**Comment by arecvlohe** [comment]
@mlms13 @andywhite37 Thanks! I am glad the previous ticket picked up some traction and it seems like there is a solution based on the second point above. Anyhow, I can be your guinea pig to see how any one of these solutions works.

**Comment by andywhite37** [comment]
Yeah, no problem, and thanks for your help.  I'm not sure if the solution (if there ends up being one) to #168 will actually help that much, as @mlms13 said - the impure modules and module aliases are only seeming to add 10% or so extra bloat to the bundle size (it seems).

This issue of module functors creating runtime objects is probably more challenging to address, and is a bit of a bummer, because our entire library is kind of built around module functors.  For some reason I was surprised that module functors resulted in runtime function calls in the .js code - I just assumed that module functors were statically resolved at compile time, and wouldn't require a runtime function call, but I don't know all the use cases of module functors, so that might just be naive.  We're brainstorming on ways to deal with these new findings, or workaround them, but not sure what the end result will be at this point.

**Comment by arecvlohe** [comment]
I think this might be related of what you all might be doing with functors.

https://bucklescript.github.io/blog/2019/10/16/another-encoding

**Comment by andywhite37** [comment]
I'm going to close this as there is no active work going on here, and there is none planned. If we have a specific thing to do, we can re-open or open a new ticket.

**Comment by mlms13** [comment]
I had started looking into this, and even have a fork somewhere that got most of Relude into a single module, but ultimately found that inlining all of a library's modules into one file [actually makes treeshaking worse](https://github.com/BuckleScript/bucklescript/issues/3550). There are a couple things that could improve this situation in the future:

- Someone could investigate "whole program" compilation in Bucklescript, which might allow _much_ better dead code elimination at the Bucklescript level, rather than relying on JS tooling. For an example of this, see the difference between [this code](https://github.com/mlms13/bsb-520-include/blob/b5a6ca0eb39fac43da2008cadfe7951c5ffec224/src/demo.bs.js) vs [the same code all in a single file](https://nit.sketch.sh/?code=LYewJgrgNgpgBAWQIYEsB2AuOBvWAXOYVTOCNFAgXgD5Ty8BfOSnAKDkPGngEk08YAJwBmSAMbwW2dh06RYcPAE8ADvADKMYCkHoA5szazZytYoDcM4-jhIwYLAAo8AGkUBKZrTyXjHG8DQTq4eXhZWsjYAXkIgWD4R-jAEIGgw8b6yDJnZrDKg8hpaOvoAogAeeIJIAM6G0sYF3IhIANaScI7qWHwCIuIwAHSa2rpoep40Rn426GKCWjD8huqDdmBdg6kw7pkcufuW+VwKvSMl4z38QqISw8VjBgDuFAAWiqrwVHDo3w0mn0Uhl+ezgNnWhkcAGpdhEAtBIQAqWHWZJwGKCECGAAMoJs20MAEYckcOE0FAARLRYqQROZQCBgIqjMqVao1QbIdqOM4PfQoyJogBuwLQ80W-EcAGYBbkZAFiJDJrQAFIcqAgPSOKmgQZC2G5IA). But ultimately, this would need to happen at the compiler rather than any change that a single library could implement.
- There is an OCaml PR for ["modular explicits"](https://github.com/ocaml/ocaml/pull/9187) which could make it much more ergonomic call functions like `Apply.map2`, so we wouldn't have to use functors to expose specialized versions such as `Option.map2`. If this happens, we could end up with quite a bit less code in Relude and much less reliance on functors.

But yeah, ultimately I've given up on trying to solve this at the Relude level for now, because it really feels like we need some help from the compiler.
