### ISSUE TITLE
Add function for voiding errors on types like Result and IO

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#180]
There are cases where you want to state that you've handled an error by marking the error type as `void`.  For `IO`, this can currently be done with something like this:

```reason
io
|> IO.mapError(errorToValue) // make the error channel the same type as the success channel
|> IO.summonError // lift the error out of the error channel, and void the error channel
|> IO.map(Result.merge) // collapse the Result in the success channel

// now we have IO.t('a, void)
```

It would be cool if there was a function like `io |> IO.handleError(errorToValue)` that did this.

The same concept applies to Result, so maybe this can be done via typeclass extensions - maybe in `MonadError`?

It might be possible to do this with just `catchError` (maybe by annotating the type?) which already exists - I'll have to try that.

**Comment by mlms13** [comment]
Real life context: I just did exactly this to produce an `IO.t(React.element, Void.t)`, to represent some async effect that is guaranteed by the compiler to produce some view that can be rendered, whether the effect succeeds or fails.

It's very possible that this fits into `MonadError`, although having to specify the error type of my IO as a module in order to get the `handleError` function might make this inconvenient enough that I'd just chain the `mapError |> summonError |> map(merge)` sequence instead. Which is kind of a bummer, but it's also reality...

**Comment by andywhite37** [comment]
Yeah, we could probably define this function at the top-level too, since it's just the one function.  We did that for the common things like map2-5 in Result, even though you also get those via ApplyExtensions in the functor.

Bummer indeed.

**Comment by andywhite37** [comment]
Added in 0.31.0.  I only added this for IO and Result for now - we can look at abstractions again some other time.
