### ISSUE TITLE
'Map.WithOrd' creates excessive closure

### ISSUE THREAD

**Issue by austindd** [reazen/relude#194]
The compiled output of the `Relude.Map.WithOrd` module functor, while convenient, creates a large closure for each application of the functor. That is to say, each call to `Relude.Map.WithOrd` will produce a new version of each function in the entire `Map` API (over 40 of them currently). This occurs within nested scopes as well as the top-level scope.

The `WithOrd` functor takes care of providing the `Comparable` module type required by Belt, while simultaneously requiring a similar module type which satisfies the `BsAbstract.Interface.ORD` signature. The resulting API is (IMO) slightly more ergonomic than that of `Belt.Map`, but not *so* much more that it justifies 40 new function allocations per map instantiation.

I know performance isn't the primary concern of this library, but you can imagine users being surprised if they use the `Map` module in any serious way, especially since this issue is not common elsewhere in the library.

I'm not sure how to solve this issue without moving the `id` type constraint into the type parameters of type `Relude.Map.t`. But if we did that, then maybe we could define all/most of the API outside of the functor ahead of time, and assign them by reference to equivalently named functions inside the constructed module.

I'm not sure if that's the best solution, but it's an idea.

**Comment by austindd** [comment]
Also, I wrote most of that before I had any coffee. Let me know if I'm mistaken or just not making sense.

**Comment by andywhite37** [comment]
@austindd - thanks for the issue.  I assume you're referencing the techniques described here:  https://bucklescript.github.io/blog/2019/10/16/another-encoding - is that right?

Yeah, we are aware of the closure issues in the library, and the runtime implications - it's unfortunate b/c we do use module functors pretty heavily, and we're trying to find a balance between convenience and other concerns like bundle size, DCE, runtime allocations, etc.

I'm personally still kind of neutral on whether to go down this road, and how/whether it might affect other places where we have module functors.  I'm not sure I'll undertake this task myself anytime soon, and I'm not sure we want to do it or not, but I think we're open to discussion (and let's discuss before anyone submits a PR).  One other concern with this approach is that this library already has a quite steep learning curve with all the abstractions, so maybe it's the case that we need to favor convenience over runtime optimizations (in some cases), and leave the raw performance to more specialized libraries?  I'm not sure I actually feel that way, but just a thought.

**Comment by austindd** [comment]
Indeed, I had that blog post in mind. I wish I had deeper knowledge of the OCaml type system, but I only know one or two possible solutions.

You bring up some really good points. I really like the broad use of module functors in this library. It's elegant and (generally) low cost. As for convenience, I guess I would break the module functor usage into two categories:

1. Interface type unification -- Using module functors to unify the `BsAbstract` module types with standard library API's is wicked cool. It's the main selling point of `Relude` in my opinion. I don't think I need to explain why that's useful to you guys, lol... But this pattern works well when these module functors are applied once and for all behind the scenes, defining their algebraic relationships ahead of time.

2. Taking type information from the API consumer -- This is what Belt is doing when it asks for `comparable` or `hashable` types. I like to think of it like this... The library provides a partially applied function to the user, who then "completes" the function with the missing type information, yielding the desired API.

The first use case is necessary for the purpose of this library, and it tends to be minimal (if not zero) cost when **all** the required type information can be known from **behind** the API boundary. This is true from a performance perspective, as well as user experience. In my humble opinion, I think all the functor usage that meets this criteria should be considered *perfectly acceptable and even desirable*.

The second use case is more of a practical design choice. Sometimes a module functor seems like the most convenient route from a library-author's perspective. But I always tend to look at API-level functors as a possible leaky abstraction. Not to mention the potential performance costs.

I think the `WithOrd` module falls into the second category, and should be re-evaluated.

Sorry for being long-winded. I just wanted to establish some common terms.

**Comment by austindd** [comment]
As for the work to be done. I am happy to help out. I've already cloned the repo and started experimenting with some different ideas.

**Comment by andywhite37** [comment]
I think I agree with your assessments, thanks for writing up your thoughts!

If you want to play around with that idea for `Map` and `Set` maybe (or even just one of those initially?), it would be interesting to see what the end result looks like. I don't want to promise that we'll end up going with it, because I'm not sure what the implications are in terms of the API and consistency with the rest of the library, but if you have the energy to try it out, it would be cool to see what it looks like.

**Comment by austindd** [comment]
Sounds good, I'll dig into it as I have time.

**Comment by andywhite37** [comment]
Ok, cool.  Maybe don't go super overboard on changes initially - I kind of just want to see what the general feel of it is before we get too far.  If it makes sense, we could add a secondary `Map` module that uses that technique, and see what it looks like compared to the current `Map`.  I'm not sure what to call it, but we can figure that out later.

**Comment by austindd** [comment]
@andywhite37, Sorry I'm just now following up on this issue. I have an implementation of the `Map` module in a cloned repo here: https://github.com/austindd/relude-map-fix/blob/master/src/Relude_Map2.re

This implementation differs in three major ways:

1. The core problem, the large closure of new function allocations, is reduced by ~75%, possibly more. This is achieved by allocating as many functions as possible *outside* of the functor's closure, and simply assigning their references to the functor's return object. By a rough count, there are currently over 40 new functions allocated by the existing `Relude.Map.WithOrd` functor. This new implementation would reduce that to 10 (some are still needed for map construction).

2. #1 was made possible by adding type parameters to the `Relude.Map.t` type, to account for the `id` and `key` types required by `Belt.Map`. The `WithOrd` functor generates those `id` and `key` types internally by creating a `Belt.Id.comparable('key, 'id)`. This allows the functor's returned module to retain the original number of type parameters (i.e. `type t('value)`), while reusing the more generic functions from the outer scope.

3. The functions in the top-level scope are available to use for all `Relude.Map.t` instances. This includes every function in the original module, with slight changes to the ones which construct new maps, which must now take a `Belt.Id.comparable` argument. Those constructors are curried with the comparable inside the `WithOrd` functor. I don't know if you want to expose those functions at the top level (in particular the `comparable` argument for constructors seems like a leaky abstraction), but the type annotations should constrain multiple maps/functions to have matching `key` & `id` types, so it should be safe.

Let me know what you think.

(Side-note: I included the Functor instance there, but we can ignore that for now. Just wanted to see if it made sense with everything else.)

**Comment by andywhite37** [comment]
I think this makes a ton of sense - thanks for sending the example!

I'm fine to move forward with this change. I think @johnhaley81 originally added the `Map` and `Set` modules to relude, so I'll just ping him via this mention to see if he has any feedback.

Do you have the time & energy to submit a PR for this and also for the `Set` module?  If not, we can get it in when someone has time.

The Functor instance makes sense.  For questions like that, I almost always just ask the question "what would purescript do" because many of these questions have already been answered there, or in other ecosystems like Haskell and Scala cats/scalaz. etc.  They have a [Functor instance](https://github.com/purescript-deprecated/purescript-maps/blob/v3.0.0/src/Data/Map.purs#L80-L83) for their Data.Map (along with other instances), so I'm happy to include that, and anything else we want to add.

**Comment by austindd** [comment]
>Do you have the time & energy to submit a PR for this and also for the Set module? If not, we can get it in when someone has time.

Absolutely. I can probably do something about it soon. I will put this in a proper fork and submit a PR soon for the `Map` module, and probably a separate one for the `Set` module. And I definitely want feedback from others if they have anything to say about it.

I might rearrange the type parameters for the top-level `t` type, to make it match `Belt`'s parameter order. But I have no idea what the standard is for phantom type parameters, if one exists. Any opinions on that?

**Comment by andywhite37** [comment]
I don't think it's important to make the types align with Belt.  I guess my gut sense would be to put phantom types last, like `t('k, 'v, 'id)`?

**Comment by austindd** [comment]
Yeah, I was putting them first, and Belt puts them last. I think last-position looks better.

**Comment by austindd** [comment]
Another idea I had for this module was to go ahead and provide Belt's `Id.MakeComparable` functor (or at least an equivalent interface), so library users don't have to go rummaging around in Belt's docs to figure out how to make a `Id.comparable('k, 'id)` type, if they decide not to use `WithOrd` for map construction.

**Comment by andywhite37** [comment]
The thing with the relude Map is that I don't think we really care about Belt in the long run.  I think Belt was used b/c they already had a Map type that we could essentially wrap with the functionality we care about.  However, someday, I could see this Map type just being replaced with a custom implementation.  I wouldn't personally endeavor to make the type in relude more convenient for use in Belt, or more tied to Belt.

**Comment by johnhaley81** [comment]
Love this change. The original implementation was to create a more FP/pipe-last ergonomic DX that leveraged type-classes instead of the `Id.MakeComparable` stuff since every time somebody on our team had to reach for it, there was a re-occurring conversation on how to use it.

Admittedly I didn't think about bundle size with the module functors getting so large. I just assumed that it would have been optimized out. However, even if it _was_ optimized out I think this is a nice change. Having the base level functions that do just work with everything is a really nice API. I'm curious to know if it makes the compiler angry until you supply all of the function args since that's pretty common with using almost anything in Belt.

And also to help provide some context with the `Belt.Map` wrapping. I did re-use the methods in `Belt.Map` specifically because it was there and it was decently fast. This of course can be rewritten if need be but I didn't think that was necessary. 

However, I wouldn't want the user to know anything about `Belt.Map` in order to use this. I agree with the idea of "don't tailor anything to how Belt works". If things line up and we can re-use then that's 💯 but otherwise let's move forward with the "Relude" way of doing things.

**Comment by austindd** [comment]
Yeah, I totally agree with you all about not exposing the Belt implementation too much. A couple of thoughts on that:

1. If we are trying to avoid leaking Belt-specific stuff from Relude's API, then we might want to just eliminate the various map-constructing functions from the top-level scope of the module. That way users won't rely on anything related to Belt's `Id` or `Map` modules. It would help Relude avoid nasty breaking changes in the future.

2. We could do some minor restructuring to *replace* those map-constructing functions with a more Relude-oriented design. E.g., much like Belt requires a `comparable` type, Relude could require an `Ord` type to be passed into functions like `make` or `fromList`.

Just some thoughts...

**Comment by johnhaley81** [comment]
It might even be possible to avoid the whole module functor thing completely if we have some sort of `Map.make((module Ord))` but I don't know what that exactly would look like and sometimes when those types aren't nailed down you can get really nasty compiler error messages.

I think having a single way to do things would be better from an API PoV and if the module functor stuff is really upping the bloat of the final JS code then maybe a complete switch to using only functions to create it? I would say that we should err on the side of better DX ultimately but if the function route doesn't yield really crazy compiler error messages and is easy to work with then I think I'd favor that.

**Comment by austindd** [comment]
I am a bit torn by that idea. Functors are a trade-off. They help with the BsAbstract typeclass implementations, and at least in this case, they do eliminate some of the headache around implementing these data structures.

In this case, I like the ergonomics of creating a new module that acts as your entire `Relude.Map` API for that specific map type. It's nice if you plan to create a lot of instances of the same type. Mostly, it's really nice to be able to create a new map using `fromList`, or whatever, and not have to create a brand-new module for it, specifying the module type, etc. Having constructor functions that take modules is less ergonomic IMO.

But idk, the all-function API might be worth exploring. I'm open-minded. :)

**Comment by austindd** [comment]
@johnhaley81, I actually like the idea of passing an `Ord` module to a `make` function. I see the appeal of that. But, at the moment, I can't think of a good way to make the conversion from a `BsAbstract.Interface.ORD` to a `Belt.Id.Comparable` inside the body of the `make` function.

I've gotten most of the way there, but the only way I could get the `Comparable.identity` type to be exposed to the internal `make` function was to create a new module functor that includes a generated `Comparable`, and have the API consumer use that new functor to create the correct module type.

Here is a minimal 

```ocaml
/**
 * Specifying the module type here, but we cannot actually use
 * this to annotate the functor type, because doing so would hide
 * the 'Comparable.identity' type required by the Belt functions.
 */
module type ComparableOrd = {
  type t;
  module Comparable: Belt.Id.Comparable with type t = t;
  type identity = Comparable.identity;
  module Ord: BsAbstract.Interface.ORD with type t = t;
  let eq: (t, t) => bool;
  let compare: (t, t) => BsAbstract.Interface.ordering;
  let cmp: Belt.Id.cmp(Comparable.t, Comparable.identity);
};

module MakeComparableOrd = (M: BsAbstract.Interface.ORD) => {
  module Ord = M;
  let eq = M.eq;
  let compare = M.compare;
  module Comparable =
    Belt.Id.MakeComparable({
      type t = M.t;
      let cmp = (a, b) => M.compare(a, b) |> Relude_Ordering.toInt;
    });
  /**
   * the phantom 'identity' type is exposed by including
   * the Comparable instance without any module interface.
   * Specifying the module interface breaks this.
   */
  include Comparable;
};

/** We can create a ComparableOrd here */
module Test = MakeComparableOrd({
  type t = int;
  let eq = a => b => a === b;
  let compare = BsAbstract.Interface.unsafe_compare;
});

/**
 * No errors when passing the ComparableOrd type to a function
 * that requires the Belt.Comparable type. The phantom 'identity'
 * type still works here
 */
let x = singleton((module Test), 42, "forty-two");

let newSingleton: type id key value. (
    (module BsAbstract.Interface.ORD with type t = key),
    key,
    value
) => (module ComparableOrd with type t = key) = (ord, key, value) => {

  // unpacking the ORD module:
  module O = (val ord: BsAbstract.Interface.ORD with type t = key);

  /**
   * Instantiate a ComparableOrd module and attempt to annotate
   * it as a Belt.Id.Comparable type. But this hides the 'identity'
   * type. Unfortunately, annotating it as the local abstract 'id'
   * type (at the top of the function) will conflict with the
   * internal phantom type generated by the functor.
   */
  let comparableOrd = (module MakeComparableOrd(O): Belt.Id.Comparable with type t = key);

  // error is thrown here:
  singleton(comparableOrd, key, value); 

};
```
(Apologies for the long code block, but I didn't think this warranted a commit to the repo, and it has dependencies which aren't hosted on external platforms.)

I don't see how we could reconcile this without forcing users to use a functor. So I'm not sure it's possible to have an API that takes the `BsAbstract.Interface.ORD` module type, internally generates the `Belt.Id.Comparable` type, and instantiates the `Belt.Map.t`.

But, as shown in the example, we could expose a functor to generate the correct module from `ORD`, and preserve the phantom type. Perhaps this could replace `WithOrd`.

Of course, I could be missing something. I'm still relatively new to this language.

**Comment by andywhite37** [comment]
Thanks for playing around with some ideas. I'm not sure what the best course is. @mlms13 have gone through similar struggles with other modules in relude, including issues with HKTs and first-class modules, etc., and I'll just put it out there that some of these things just don't have a natural/ergonomic/elegant representation in Reason/OCaml.

My feeling is that `Belt.Map` already exists, and already does it's thing with the phantom type, so I don't feel strongly that we need to capture all those semantics as-is in Relude. Yes, this means that Relude has some less-desirable closures and slightly bigger bundle sizes, but there are tradeoffs in API consistency, "ergonomics," performance, etc. I think Relude falls more into the API consistency camp, sometimes at the expense of performance and bundle size. That said, if there is an implementation option that is clearly better in terms of performance, and doesn't go too far off the rails in terms of the API, I'm open to doing it. The other thing I'd note is that you are more than welcome to make your own libraries using the abstractions from bs-abstract and whatever extensions you want to use from relude, and do things however you want, so don't feel like you need to fight tooth and nail to get this in here.

It's been a struggle to try to make all the concepts from languages like purescript and haskell work in the language, and at some point we have to draw the line and say, "if we really want this, we should be using a more capable language." Performance and bundle size is important, but it's not the primary goal of this library to optimize on those factors. Module functors are an imperfect means to an end, and are not the same as typeclasses in other languages.

I'm not trying to discourage your efforts, but I'm more keen on keeping the API simple and consistent in relude. If there are performance problems, we can look into them as needed, and with a pragmatic eye, which we have done before. I'd highly encourage you to check out haskell or purescript though, because I think you are running into things that you would find to be very cool and mind-blowing in those languages.

The above are just my opinions - I don't speak for relude or obviously reason as a whole.

**Comment by austindd** [comment]
@andywhite37 That's totally fair. At this point, I'm not concerned about performance to the point that it's a major issue for me, personally. I would like to see BuckleScript manage a lot of the performance optimizations for us, so that we don't have to think about it too much.

I did try out PureScript for a while, and I did like some of the features it offered. But I think I'm more comfortable with Reason. It's my favorite language at this point in time, so I want to see it really shine wherever possible.

All of that said. The original example I posted still works well. It compiles (which is not always a trivial matter, lol...), improves performance, and preserves the original API, as far as I can tell. Which is to say, I think the original suggested change is technically non-breaking, since it preserves the type signatures of the original functions inside the `WithOrd` functor, and just adds many of those functions to the top-level scope. But I could be wrong about that.

If that's the case, then I see no compelling reason not to merge that version, at the very least. What do you think?

**Comment by andywhite37** [comment]
Thanks @austindd - yeah, the stuff you linked to here https://github.com/austindd/relude-map-fix/blob/master/src/Relude_Map2.re seemed good to me - a good compromise on performance and other factors. I'd be happy to merge that and an equivalent implementation for Set, which could be done separately, but it would be nice for those things to be consistent.
