### ISSUE TITLE
IO APPLY typeclass doesn't run in parallel

### ISSUE THREAD

**Issue by johnhaley81** [reazen/relude#196]
So while doing some testing today I saw that the `IO.mapTupleX` wasn't running in parallel. I.e. IO's are executed in serial. After digging around a little it looks like (I _think_) that there might need to be a new constructor possibly to handle parallel execution? I'm not totally sure but I wanted to bring this up at least and start a conversation.

**Comment by andywhite37** [comment]
Thanks for the issue.  It's funny you bring this up, because I actually just noticed this too when I was looking at the `IO` implementation again.

I'm pretty sure this is happening b/c I implemented `apply` in terms of `flatMap` (which is something you can do, but it often changes the semantics of `apply`):

https://github.com/reazen/relude/blob/cc0501eb81b6404d75ad4bd98bac4d87e0c4d26d/src/Relude_IO.re#L156

Using `flatMap` forces what could (and should) be parallel semantics into sequential.  I'm pretty sure I did this because implementing `apply` with `flatMap` was much simpler than doing it the "correct" parallel way, which I think for `IO` might require pattern matching all the possible combos of `IO`, which is a little painful.  I think in hindsight, I would have made `IO` have fewer constructors, but oh well!

```reason
let apply = (ioF, ioA) => switch(ioF, ioA) {
  | (Pure(f), Pure(a)) => Pure(f(a))
  | (Pure(f), Suspend(getA) => Suspend(() => f(getA()))
  | ... // TODO: match all other cases
};
```

I'm not 100% sure this is what's going on, but I strongly suspect it is.  It should be possible to implement `apply` properly for parallel semantics to fix this issue.

**Comment by andywhite37** [comment]
I'm going to call this an enhancement rather than bug, b/c it's working as expected based on how it's written, but the semantics are undesirable.

**Comment by andywhite37** [comment]
@johnhaley81 - let me know if you're interested in taking a stab at this, otherwise I can try to do it sometime this week.

**Comment by johnhaley81** [comment]
I'd love to dig into this a bit but I don't know if I'm able to figure out how to run IO's in parallel without hitting the `unsafeRunAsync` function. If that's the case then it feels like there kind of needs to be another variant constructor (`Apply(t('r => 'a, 'e), t('r, 'e)): t('a, 'e)`) but that makes a lot of the functions in `Relude_IO.re` really big.

Maybe the number of constructors should be reduced in there to just the smallest amount needed? Things like `Pure`, `Map`, and `FlatMap` make sense but `Suspend` and `SuspendIO` can be implemented using map/flatMap.

```ocaml
let suspend = getA => pure() >> map(getA);
let suspendIO = getIOA => pure() >> flatMap(getIOA);
```

Just removing those 2 make the switch statements much less complex.

**Comment by andywhite37** [comment]
Yeah, that could be that we need the `Apply` constructor.  I'll take a stab at some changes and see if I can get something going.

**Comment by johnhaley81** [comment]
Sounds good. I have a solution in my head for it but it does revolve around adding another constructor. LMK if you need a hand with anything.

**Comment by johnhaley81** [comment]
To see if we could even remove the `Suspend` and `SuspendIO` constructors I WIP'ed up #197

**Comment by andywhite37** [comment]
Yeah, that is an option, but I want to play around with `Apply` a little more before deciding whether to slim down the constructors.  It might make sense to do some benchmarking to see what kinds of impacts certain changes will have before making decisions like this.

**Comment by andywhite37** [comment]
I'm hoping to get back into this sometime this week - I took some time off for Thanksgiving, then I got sick.

**Comment by andywhite37** [comment]
Initial release in v0.40

**Comment by andywhite37** [comment]
Sorry, I meant to leave this open.  @johnhaley81 - let me know when you get a chance to try out v0.40.0, and if you have any feedback (including things like "it doesn't work" :smile: )

**Comment by andywhite37** [comment]
I'll go ahead and close this, but we can re-open if there are outstanding issues.

**Comment by johnhaley81** [comment]
I know this is closed but I just wanted to confirm and say that we have this live in production and it's working 💯
