### ISSUE TITLE
Bikeshedding: Rename `filterNot` to `reject` plez :pray:

### ISSUE THREAD

**Issue by erlandsona** [reazen/relude#243]
https://github.com/reazen/relude/blob/cc0501eb81b6404d75ad4bd98bac4d87e0c4d26d/src/list/Relude_List_Base.re#L214

**Comment by andywhite37** [comment]
How about we alias it? Would that work?

**Comment by mlms13** [comment]
The funny thing is, I actually like Belt's `keep` name better than `filter`, since `filter`'s intention isn't clear (based on its name alone), unless you already know what to expect. `keep` and `reject` have nice symmetry, and are probably more intuitive than `filter` and `filterNot`, so I'm all for aliasing both of them.

**Comment by andywhite37** [comment]
Ok, I can do this real quick - I'm in there now

**Comment by kyldvs** [comment]
Another naming option is:

- `filterKeep` (true keeps it)
- `filterDrop` (true drops it)

This I think is a little more clear than `filter` and it keeps the familiar "filter" name at the start of each to help people find the functions.
