### ISSUE TITLE
Help: List.IO.sequence / IOE.all, but ignore errors

### ISSUE THREAD

**Issue by floscr** [reazen/relude#292]
Fantastic library first of all!
I'm having a bit of trouble wrapping my head around the IO Type:

There's the List Extension `List.IO.sequence` which returns an error if one of the IO items in the list fails.
Is it possible to return only the successful IO types and ignore errors (and perfectly execute an side effect for all the errors) ?

I can't simply filter the list, as it's constructed of Async values.

Help would be much appreciated :bow:

**Comment by johnhaley81** [comment]
Since you need the error in the success channel, I think something like `IO.summonError` would work well here. Then you could remove the ones that failed inside of the IO. Something like:

```reasonml
[IO.pure(1), IO.throw("bad")]
|> List.map(IO.summonError)
|> List.IO.sequence
|> IO.map(List.mapOption(Result.getOk))
```

Which would give you a `IO.t(list(int), Void.t)`. The `Void.t` in the error just means that this cannot fail which is what happens when you summon the error.

**Comment by floscr** [comment]
Fantastic, that works for me!
Thanks for the quick answer :+1:
