### ISSUE TITLE
Documentation HTML files hang in Firefox

### ISSUE THREAD

**Issue by jdeisenberg** [reazen/relude#45]
1. Forked reazen/relude
2. Cloned the fork
3. Went to Mozilla Firefox 67.0b4 (64-bit) on Fedora 29
4. Entered URL: `file:///home/david/reasonlab/relude/docs/api/Relude.html`
5. Page does not plot; displays “loading circle” animation. Web console shows no error messages.

Works correctly on Chrome Version 73.0.3683.75 (Official Build) (64-bit)

**Comment by mlms13** [comment]
You may need to `rm -rf ./docs && redoc` if you haven't already. I'm also using Firefox 64-bit on Ubuntu (but version 65, so maybe there's a difference there), and I'm not seeing the issue, but to be honest I'm not quite sure what all I did to get the docs into their current state locally.

Our redoc docs barely exist at this point, and I think @andywhite37 was running into some issues with `redoc` on NixOS, so we haven't invested a ton of effort in getting things working. I think we're interested in trying `odoc`, especially if [Bucklescript adds better support for it](https://github.com/BuckleScript/bucklescript/issues/3198).

**Comment by jdeisenberg** [comment]
Oh, I was going to start writing Redoc/markdown style documentation tomorrow!  Does `odoc` support ReasonML in the doc strings?

**Comment by andywhite37** [comment]
Yeah, I think I actually removed redoc as a dependency, but didn't clean up the actual documentation files that were previously generated.  I think I can add redoc back for now, but I don't recall what the original issue was.  I'll try it again tomorrow and report back.

**Comment by andywhite37** [comment]
@jdeisenberg - I didn't see your second comment when I posted mine - we must have been writing them at the same time.

Like @mlms13 said, our current thinking on docs was to wait to see what happens with [bsdoc](https://ostera.github.io/bsdoc/docs/BsDoc/) getting more [closely integrated](https://github.com/BuckleScript/bucklescript/issues/3198) with the bucklescript ecosystem, and ideally not requiring `opam` in addition to `npm` for installing packages.  The reason we're targeting `odoc`/`bsdoc` over `redoc` is that it seems to be the tool of choice for OCaml documentation, but we weren't super excited about having to depend on `opam` in addition to everything else you need in bucklescript.

If I take your comment to mean that you were plannign on writing docs for relude stuff, that's awesome!  It might make sense to target the bsdoc style of documentation (which I haven't personally looked at much).

**Comment by jdeisenberg** [comment]
I am confused here. Does `odoc` use document comments written in ocamldoc (http://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html) format? If so, how does this address the problem of writing documentation for ReasonML code?

**Comment by andywhite37** [comment]
I haven't attempted to write documentation for Reason code that can be extracted by any tool.  When we setup the project, we arbitrarily picked `redoc` as a thing to try, and when I ran that tool against the code, it generated some documentation html purely based on the types and function signatures in the code, and whatever random comments happened to be in the right format.  This was basically just a trial of that tool, and not something we planned to stick with forever.

The `redoc` code seemed to have a fairly deep dependency tree, and the code was not straightforward for us to understand, so we were not super jazzed about it.  In the meantime, we became aware of the `bsdoc`/`odoc` effort, which seemed to have a goal of becoming a more standardized documentation tool.  We liked that idea, so we basically put documentation on hold to see how that panned out.

Since the project is in a bit of flux in terms of moving things around, documentation is not high on our proirity list at the moment, and we haven't put a ton of thought towards it.

I honestly don't know much about `odoc` - we are mainly interested in using a tool that will be well-supported and widely used, but we don't want to have to adopt extra package installer dependencies like `opam` in order to do that.

**Comment by andywhite37** [comment]
In summary, I don't want to discourage anyone from writing documentation or contributing in any way, but we basically don't know what we're doing yet in terms of documentation, so I'm not sure what kind of direction or advice to offer.

**Comment by jdeisenberg** [comment]
I really like the way `redoc`’s output looks. How about if I write doc comments (`/** ... */`) using markdown, as that’s a fairly standard format? I will use only ReasonML in examples, as I suspect you have designed it primarily for ReasonML programmers rather than the OCaml crowd.

**Comment by andywhite37** [comment]
That sounds good, thank you again for your offer to help!

**Comment by andywhite37** [comment]
@jdeisenberg - I just pushed a commit that re-added `redoc` to our package.json.  If you pull master and re-run `npm install`, you should then be able to run `npm run docs`, which is a simple script we have to generate the docs.

**Comment by mlms13** [comment]
Since you've been able to generate some docs, I assume the issue with the page hanging in Firefox is no longer a thing, @jdeisenberg? Reopen if that isn't the case. :slightly_smiling_face:
