### ISSUE TITLE
Tuple utilities

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#68]
It would be handy to add some helpers for dealing with tuples.

One thing I can think of off the top of my head is a set of applicative `map2/map3/etc.` functions for a tuple.  It will unfortunately have to use a module functor to get the applicative behavior, but we can add some specializations e.g. (pseudocode):

```
let fa: option(int) = Some(1);
let fb: option(int) = Some(2);
let fc: option(int) = (fa, fb) |> Relude.Tuple.Option.map2((a, b) => a + b));
```

Or maybe it should be `Relude.Option.Tuple`?

This would be equivalent to `Relude.Option.map2((a, b) => a + b, fa, fb)` but with better chainability and readability.

**Comment by andywhite37** [comment]
This effort should probably be done as some sort of extension that you get for free when you have an Applicative/Monad/etc.

**Comment by mlms13** [comment]
In `bs-decode` I'm finding myself writing a lot of `map4((a, b, c, d) => (a, b, c, d), ...)` so having simple tuple constructors like `Relude.Tuple.make4` would save me a lot of parentheses and commas.

Similarly, a tuple constructor that looks for arrays or lists of a specific size would be pretty handy. This would be a bit like `List.takeExactly(4)` but instead of a new list, it would return `option(('a, 'a, 'a, 'a))`. I'm playing around with this in `bs-decode`, and if it works out, I'll move it here.

**Comment by mlms13** [comment]
I just pushed a `Relude_Tuple` module, which is basically just helpers for constructing tuples (from n-ary functions, arrays, and lists).

**Comment by andywhite37** [comment]
I'm going to try to add the `mapTuple2` etc. to ApplyExtensions tonight, and then we can close this ticket for good.

This will sort of be like the `map2`/etc. functions, but will have a more "fluent" usage, like below.

`(Some(1), Some(2)) |> Option.mapTuple2((a, b) => a + b)`

compared to:

`Option.map2((a, b) => a + b, Some(1), Some(2))`

**Comment by andywhite37** [comment]
Ok, I added some more stuff in 0.16.0, so I'll close this for now
