### ISSUE TITLE
Option

### ISSUE THREAD

**Issue by mlms13** [reazen/relude#7]
I'm going to run through all of the option utilities I've used and written recently and make a list of all of the helper functions here:

- [x] `(b, a => b, f(a)) => b`
  - `fold` in Scala
  - `maybe` in PureScript and bs-abstract
  - `mapWithDefault` in Belt
  - `unwrap` in Elm (Maybe.Extra)
  - `map_default` in Batteries
  - `cata` in Thx

- [x] `(a, f(a)) => a`
  - `getOrElse` in Scala and Thx
  - `fromMaybe` in PureScript
  - `withDefault` in Elm
  - `getWithDefault` in Belt
  - `default` in Batteries
  - infix `(|?)` in bs-abstract

- [x] `((b, a) => b, b, f(a)) => b` (traditional fold left, is this even useful?)
  - `foldLeft` in Scala (not sure if it's present for Option)
  - `foldl` in PureScript (and Elm, but not present for Maybe)
  - `fold_left` in bs-abstract
  - `reduce` in Belt and fantasy-land, but not present for Option

- [x] `(f(a), f(a)) => f(a)`
  - `alt` in PureScript, bs-abstract, fantasy-land
  - `or` in Elm (Maybe.Extra)
  - flipped as `orElse` in Elm (Maybe.Extra)

- [x] `(a => b, f(a)) => f(b)`
  - `map` pretty much everywhere

- [x] `(f(a => b), f(a)) => f(b)`
  - `ap` in PureScript and fantasy-land
  - `apply` in bs-abstract
  - `andMap` in Elm (Maybe.Extra)

- [x] `a => f(a)`
  - `pure` in PureScript and bs-abstract
  - `of` in fantasy-land
  - doesn't appear to exist in Belt or Elm

- [x] `(a => f(b), f(a)) => f(b)`
  - `flatMap` in Scala and Belt
  - `flat_map` (flipped) in bs-abstract
  - `bind` (flipped) in PureScript and Batteries
  - `andThen` in Elm
  - `chain` in fantasy-land

- [x] `((a, b) => c, f(a), f(b)) => f(c)` and friends
  - `map2` in Elm
  - `lift2` in PureScript and bs-abstract
  - `liftA2` in Haskell
  - `ap2` in Thx

- [x] `toList`
- [x] `toArray`
- [ ] lazy versions of `maybe` and `default`
- [x] `isSome`
- [x] `isNone`
- [x] `filter`
- [x] `join`
- [x] infix functions
  - [x] alt
  - [x] default (flipped)
  - [x] map
  - [x] ap
  - [x] flatMap (flipped)

**Comment by andywhite37** [comment]
I'm going to run through all of the option utilities I've used and written recently and make a list of all of the helper functions here:

- [ ] `(b, a => b, f(a)) => b`
  - `fold`

- [ ] `(a, f(a)) => a`
  - `getOrElse`
   - infix `(|?)` in bs-abstract

- [ ] `((b, a) => b, b, f(a)) => b` (traditional fold left, is this even useful?)
  - `foldLeft` in Scala (not sure if it's present for Option)
  - In general I think I like the name `reduce` when you don't have to provide the initial value, like when you're dealing with a NonEmpty or a Monoid, and `fold*` when you provide the initial value.
  
- [ ] `(f(a), f(a)) => f(a)`
  - `alt` in PureScript, bs-abstract, fantasy-land
  - `or` in Elm (Maybe.Extra)
  - flipped as `orElse` in Elm (Maybe.Extra)
  - I like `alt`, `or`, or `orElse` - if we choose `getOrElse` above, maybe `orElse` makes sense?

- [ ] `(a => b, f(a)) => f(b)`
  - `map` pretty much everywhere

- [ ] `(f(a => b), f(a)) => f(b)`
  - `apply` in bs-abstract

- [ ] `a => f(a)`
  - `pure` in PureScript and bs-abstract
  - `of` in fantasy-land
  - I like `pure` for FP reasons, but I also like `of` for constructing any type from a single value.  Maybe this could be one of our rare aliases, since `pure` is not super intuitive to newbies.

- [ ] `(a => f(b), f(a)) => f(b)`
  - `flatMap` in Scala and Belt
  - `bind` (flipped) in PureScript and Batteries
  - I think I prefer `flatMap` b/c it's more descriptive of what it does... but `bind` is okay too

- [ ] `((a, b) => c, f(a), f(b)) => f(c)` and friends
  - `map2` in Elm
  - I like the mapN conventions from Elm

- [ ] `toList`
- [ ] `toArray`
- [ ] `eq` (not needed?)
- [ ] lazy versions of `maybe` and `default`
- [ ] `isSome`
- [ ] `isNone`
- [ ] `filter`
- [ ] `join`
  - I think I like `flatten` over `join` for the `f(f(a)) => f(a)` functions... mostly because it makes sense alongside `flatMap`
- [ ] infix functions
  - [ ] alt
  - [ ] default (flipped)
  - [ ] map
  - [ ] ap
  - [ ] flatMap (flipped)

**Comment by mlms13** [comment]
I skipped `eq` because the `==` should already work well enough, but I'm willing to reconsider. I should add tests as well, but I'm pushing what I have for now.

I'm also skipping the lazy versions of `fold` and `getOrElse` mostly because I'm not sure what to call them.

**Comment by mlms13** [comment]
I ended up adding eq (and the EQ-module-friendly version), but I'm going to keep skipping laziness, at least for now.
