### ISSUE TITLE
Reuse Relude_Foldables and Relude_Monads (and friends) in more places

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#72]

**Comment by mlms13** [comment]
Hmm, I should really start working on this. It's been bugging me that `Result.flatten` doesn't exist.

**Comment by andywhite37** [comment]
Before you jump into changes, can we discuss what this entails for things like `Result` and presumably many other similar types?  I just want to understand what changes you anticipate making, and make sure it's the right direction for everything to go.  Is it as simple as putting something like `include Relude_Extensions_Monad.MonadExtensions(Monad)` at the bottom of the `Result_Result.re` file?  Or does it require us to break up the module into the `_Instances.re`/`_Base.re`/`_Extensions.re` etc. files, and add the .rei files like we did for `List` and `Array`?

I haven't had a chance to play around and understand the organization of `List` and `Array` too much yet, but I need to take a closer look to understand it better.

I was also wondering if there are any other ways in the OCaml module system to `include` extra bits of functionality like this.  I was wondering if `module type`s could somehow allow you to add base implementations of things if you just implement the module type (sort of like traits in scala).  E.g. in the `MONAD` module type, I was curious if you could just add a `flatten` function which is implemented in terms of `flatMap`/`bind`, sort of like how Haskell typeclasses can include things implemented in terms of other things, and you just have to implement the minimal set of operations to satisfy everything else.  I'm not sure if that's a thing, but I wanted to look into it.

I also still feel a tiny bit of resistance in my heart at the idea of adding .rei files for every module, just because of the duplication and maintenance burden it brings.  I get the point of them, but I'm still struggling to get on board.  I could probably be convinced though.

**Comment by mlms13** [comment]
### What does this entail?

At the moment, mostly just:

```reason
// Relude_Result.re
module MonadExtensions = Relude_Extensions_Monad.Make(Monad);
let flatten: Result.t(Result.t('a, 'e), 'e) => Result.t('a) = MonadExtensions.flatten;
// map2, map3, flap, etc...
```

I don't think we'd have to break up any existing files. I think the only reason we did that with Array/List was to make it easier for other modules to use their base functionality without running into circular dependencies. PureScript doesn't break Either/Maybe into multiple files, so I doubt we'd have to.

I think it would be more ideal to just do:

```reason
// Relude_Result.re
include Relude_Extensions_Monad.Make(Monad);
```

But for now we can't do that, because including `Relude_Extensions_Monad` brings its `Infix` module, which conflicts with `Relude_Result.Infix`. We could fix this (I'd kind of like to, because it would feel more in the spirit of typeclasses to do it this way), but if we do so, we'd probably want an `rei` file to avoid the gross inferred type signatures that come from module-level functions. Also, if we don't have an `rei` file in that case, there's nowhere for the docs to live.

### Alternative approaches

OCaml `module type`s are like interfaces in that they can only have signatures, no implementations (as far as I know). So I don't think you can build `flatten` at the `MONAD` module type definition. I think the closest you can get is the module functor approach that we/bs-abstract are taking. Unless you go in a [completely different direction](http://ocamllabs.io/higher/lightweight-higher-kinded-polymorphism.pdf) (e.g. [higher](https://github.com/ocamllabs/higher)).

But on the topic of Scala-style traits, this is a syntax error in Reason:

```reason
module type Monad = {
  type t('a);
  let bind: ('a => t('b), t('a)) => t('b);
  let flatten = mma => bind(a => a, mma); // parser doesn't like this
};
```

### Interface files

Yeah, I'm not super sold on them either, but if we're going to be deriving functionality from typeclass membership, it's kind of the only way to have docs and sane type signatures. Also, rei files seem pretty well-supported by tooling (e.g. I've been getting nice documentation tooltips for List/Array functions in vscode).

I do kind of like that type signatures and docs don't have to clutter up the implementation files if we start moving to interfaces. Plus, universal quantification works as expected. I've been trying to catch and fix places where we're missing `'a. ...` in annotations, but there are still quite a few left.

**Comment by mlms13** [comment]
Well that was the mega comment. Here are some more concrete options for next steps:

- [ ] Build our own typeclass "Extensions" modules for Functor/Apply/Monad, similar to what we have for Foldable. This would allow us to have more control over naming (e.g. we're currently aliasing `lift2` as `map2` by hand everywhere we generate that function. Also, we could handle the `Infix` submodule differently so it would be easier to `include` all of the extension module functions
- [ ] Either `include` or pick out and alias specific functions from monad extensions in `Option`, `Result`, `AsyncData`, `AsyncResult`, possibly elsewhere
- [ ] `include` or alias functions from foldable extensions in Option and Result... maybe Async* modules as well? I haven't really thought that through
- [ ] If we go the `include` route instead of aliasing specific functions, we'll probably need rei files, but we don't have to take this approach for now.

**Comment by andywhite37** [comment]
Got it - thanks for the explanation.  I get the issue with the Infix operators too - it would be nice to fix that so we can just include things and not have to re-alias them (although by re-aliasing, at least you know what you're getting).  I think you're right that maybe we should build our own "extension" framework, so we can control exactly how it works, rather than re-packaging the stuff from bs-abstract.  I like that including those things gives you everything they provide, but I dislike that you don't explicitly know what you are getting, and I'm not sure if there's a way to guarantee that your .rei file exposes everything that you've included, is there?

Btw - I still like the `Make` approach for the extensions, but when I tried to go that direction with the `Foldable` extensions, it got kind of messy and weird with the sub-extensions like `FoldableMonoid`, etc.  Like when you include the `FoldableExtensions` into your module, it wasn't clear what the sub-extensions should be called - `MakeMonoid` or `OfMonoid` ended up feeling weird because they kind of lost the notion that it was related to `Foldable` (since those things came in via `include`), and it's possible that other extensions might have things like `MakeMonoid`/`OfMonoid` so the names might conflict.  Maybe you can poke around with it and try some other ideas.  I kind of settled on just naming everything more explicitly, so it was obvious what things were when they were getting included.  Maybe it would be cleaner to not have the sub-modules nested inside the FoldableExtensions - maybe we should have `FoldableExtensions.Make(Foldable)` and `FoldableMonoidExtensions.Make(Foldable, Monoid)` as standalone things, rather than nested - that would make the `Make` approach a little more feasible I think?  The tradeoff would be that you don't get the sub-extensions when you `include FoldableExtensions`, but maybe that is actually a good thing - I kind of prefer more explicit includes rather than mega nested includes, but I get the tradeoff there.

After reading your comment, I think I'm more sold on the .rei files now too.  My personal preference is to annotate the types even in the .re modules, because I find the code much easier to read and understand when the types are annotated at least at the function level.  I'm not sure how to reach a compromise on that front :confused: - I find the type annotations to be critical rather than clutter.

One final point - the main thing I really dislike about the .rei workflow is that whenever you might want to re-gen the .rei file to see if you are missing anything, you lose all the docs... I wish there was a better way to manage the .rei files, or make sure they are exposing "everything" (except the stuff you don't want to expose of course :smiley:), and retain all the docs...  it's the classic problem of editing files that were once generated...

**Comment by mlms13** [comment]
I'm totally fine with keeping type annotations in the `re` files even if we add more `rei` files. Personally, I don't mind letting the compiler infer types and having `rei` as a confirmation that the inferred type matches expectations, but I can also see the value in keeping annotations close to the implementations. :+1: Mostly, I just find the docs to be a lot to scroll through, and I wouldn't mind moving them to `rei` files whenever it makes sense. I think some doc generation tools might prefer this approach, even?

I wonder if tools exist to check for missing functions between `re` and `rei` files, because I agree that it's a real bummer that the auto-generation is basically a one-time thing. If we add a "for free" function to the foldable extensions module, things that `include` it should automatically get that function... we shouldn't have to track down every implementation of foldable and manually add the new function. Mostly I just want rei files to weed out nested submodules that shouldn't be exposed externally (and to make sure type signatures for `include`d functions aren't completely insane).

**Comment by andywhite37** [comment]
I agree it would be nice to get the docs out of the impl files.

**Comment by andywhite37** [comment]
I'll close this ticket in favor of a few discussion tickets, and we'll see what specific actions fall out of that.
